server:
  port: 8081
spring:
  application:
    name: food_city

  datasource:
    url: jdbc:postgresql://localhost:5432/food_city
    username: food_user
    password: food_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
user:
  cadastro:
    cliente: "CLIENTE"
    proprietario: "PROPRIETARIO"
    funcionario: "FUNCIONARIO"

kind: Application


